question_data = [{"category": "Science: Computers", "type": "boolean",
                  "difficulty": "medium",
                  "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard "
                              "Mark II computer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Pointers were not used in the original C programming language; they were added later "
                              "on in C++.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "DHCP stands for Dynamic Host Configuration Port.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Windows ME operating system was released in the year 2000.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen "
                              "resolution.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, "
                              "Android, and Chrome OS.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The Python programming language gets its name from the British comedy group "
                              "&quot;Monty Python.&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
